# Generated by Django 4.1.7 on 2023-03-10 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecin', '__first__'),
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('num_rendez_vous', models.AutoField(primary_key=True, serialize=False)),
                ('date_rendez_vous', models.DateTimeField()),
                ('num_medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecin.medecin')),
                ('num_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('num_prescription', models.AutoField(primary_key=True, serialize=False)),
                ('description_prescription', models.TextField()),
                ('num_medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecin.medecin')),
                ('num_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Examiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_examen', models.DateTimeField(auto_now_add=True)),
                ('type_examen', models.CharField(max_length=50)),
                ('diagnostic_examen', models.TextField()),
                ('num_medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecin.medecin')),
                ('num_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.patient')),
            ],
        ),
        migrations.AddConstraint(
            model_name='examiner',
            constraint=models.UniqueConstraint(fields=('num_patient', 'num_medecin', 'date_examen'), name='patient_medecin_date_examen_unique'),
        ),
    ]
