# Generated by Django 4.1.7 on 2023-03-10 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecin', '0001_initial'),
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('type_operation', models.CharField(max_length=255)),
                ('num_medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecin.medecin')),
                ('num_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.patient')),
            ],
        ),
        migrations.AddConstraint(
            model_name='operer',
            constraint=models.UniqueConstraint(fields=('num_patient', 'num_medecin', 'date_operation'), name='patient_medecin_date_operation_unique'),
        ),
    ]
