# Generated by Django 4.1.7 on 2023-03-10 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecin', '__first__'),
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitaliser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_hospitalisation', models.DateTimeField(auto_now_add=True)),
                ('date_fin_hospitalisation', models.DateTimeField(blank=True, null=True)),
                ('num_medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecin.medecin')),
                ('num_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.patient')),
            ],
        ),
        migrations.AddConstraint(
            model_name='hospitaliser',
            constraint=models.UniqueConstraint(fields=('num_patient', 'num_medecin', 'date_debut_hospitalisation'), name='patient_medecin_date_debut_hospitalisation_unique'),
        ),
    ]
