# Generated by Django 4.1.7 on 2023-03-10 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('num_horaire', models.AutoField(primary_key=True, serialize=False)),
                ('jour_horaire', models.CharField(max_length=10)),
                ('heure_horaire', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('num_medecin', models.AutoField(primary_key=True, serialize=False)),
                ('num_medecin_chef', models.IntegerField()),
                ('nom_medecin', models.CharField(max_length=20)),
                ('prenom_medecin', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('nom_poste', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('salaire', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(max_length=50)),
                ('domaine', models.CharField(max_length=50)),
                ('type_intervention', models.CharField(max_length=50)),
                ('num_medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecin.medecin')),
            ],
        ),
        migrations.AddField(
            model_name='medecin',
            name='nom_poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecin.poste'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('num_cheque', models.AutoField(primary_key=True, serialize=False)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('date_expiration', models.DateField()),
                ('montant_cheque', models.FloatField()),
                ('num_medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecin.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='Attribuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_horaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecin.horaire')),
                ('num_medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecin.medecin')),
            ],
        ),
        migrations.AddConstraint(
            model_name='specialiser',
            constraint=models.UniqueConstraint(fields=('specialite', 'num_medecin', 'domaine'), name='specialite_medecin_domaine_unique'),
        ),
        migrations.AddConstraint(
            model_name='attribuer',
            constraint=models.UniqueConstraint(fields=('num_horaire', 'num_medecin'), name='horaire_medecin_unique'),
        ),
    ]
