# Generated by Django 4.1.7 on 2023-03-10 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecin', '__first__'),
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('num_dossier', models.AutoField(primary_key=True, serialize=False)),
                ('etat_dossier', models.BooleanField(default=True)),
                ('num_patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accueil.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Consulter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('tension_corporelle', models.FloatField()),
                ('resultat_consultation', models.TextField()),
                ('num_medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecin.medecin')),
                ('num_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.patient')),
            ],
        ),
        migrations.AddConstraint(
            model_name='consulter',
            constraint=models.UniqueConstraint(fields=('num_patient', 'num_medecin', 'date_consultation'), name='patient_medecin_date_consultation_unique'),
        ),
    ]
